<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <BaseOutputPath>.\..\..\生成\PMCSsE_Frontend_AvaloniaUI.Browser</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PMCSsE_Frontend_AvaloniaUI\PMCSsE_Frontend_AvaloniaUI.csproj" />
  </ItemGroup>
</Project>
