<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <ApplicationIcon>PMCSsE.ico</ApplicationIcon>
    <BaseOutputPath>D:\Desktop\生成\PMCSsE_前端_WPF</BaseOutputPath>
    <Version>1.0.4</Version>
    <Authors>八宝粥</Authors>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="PMCSsE.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PMCSsE_FrontendAndBackendCommunicator">
      <HintPath>..\Library\PMCSsE_FrontendAndBackendCommunicator\PMCSsE_FrontendAndBackendCommunicator.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icon\AppIcon_About.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_AddNewMCServer.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Cancel.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Clean.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Close.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Console.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Copy.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_ExitApp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Finish.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Folder.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Forge.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_FunctionListBoxItem.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_FunctionListClosed.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_FunctionListOpened.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Generator.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Help.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_KillMCServer.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Login.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Maximize.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Messages.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Minimize.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_OpenManager.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_OpenWebsite.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_RemoveMCServer.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_RunMCServer.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Settings.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Settings1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_ShutdownMCServer.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_Store.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\AppIcon_VanillaMCServer.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icon\Author_BBZ.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\AppImage_Background.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\AppImage_Background1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\AppImage_Background2.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\CustomButton.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\CustomListBoxControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\CustomListBoxItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\ImageButton.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\LogListBoxItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\SingleMCServerViewerControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Windows\AddNewMCServerWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Windows\AppAboutWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Windows\SetSingleMCServerWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Windows\MCServerManagerWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Windows\StartArgumentGeneratorWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Windows\UserLoginInWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Style\ImageButtonStyle.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
